import random
from datetime import datetime, timedelta

airpotr_list = [
    {'iata_code': 'AAQ', 'name': 'Анапа', 'country': 'Россия'},
    {'iata_code': 'ABA', 'name': 'Абакан', 'country': 'Россия'},
    {'iata_code': 'ADB', 'name': 'Измир', 'country': 'Турция'},
    {'iata_code': 'ADH', 'name': 'Алдан', 'country': 'Россия'},
    {'iata_code': 'AER', 'name': 'Сочи', 'country': 'Россия'},
    {'iata_code': 'AFS', 'name': 'Зарафшан', 'country': 'Узбекистан'},
    {'iata_code': 'AKX', 'name': 'Актобе', 'country': 'Казахстан'},
    {'iata_code': 'ALA', 'name': 'Алматы', 'country': 'Казахстан'},
    {'iata_code': 'AMV', 'name': 'Амдерма', 'country': 'Россия'},
    {'iata_code': 'ARH', 'name': 'Архангельск', 'country': 'Россия'},
    {'iata_code': 'ASB', 'name': 'Ашхабад', 'country': 'Туркменистан'},
    {'iata_code': 'ASF', 'name': 'Астрахань', 'country': 'Россия'},
    {'iata_code': 'ATH', 'name': 'Афины', 'country': 'Греция'},
    {'iata_code': 'AYT', 'name': 'Анталия', 'country': 'Турция'},
    {'iata_code': 'AZN', 'name': 'Андижан', 'country': 'Узбекистан'},
    {'iata_code': 'BХY', 'name': 'Байконур (Крайний)', 'country': 'Казахстан'},
    {'iata_code': 'BAX', 'name': 'Барнаул', 'country': 'Россия'},
    {'iata_code': 'BGN', 'name': 'Белая гора', 'country': 'Россия'},
    {'iata_code': 'BHХ', 'name': 'Балхаш', 'country': 'Казахстан'},
    {'iata_code': 'BHK', 'name': 'Бухара', 'country': 'Узбекистан'},
    {'iata_code': 'BJV', 'name': 'Бодрум', 'country': 'Турция'},
    {'iata_code': 'BQG', 'name': 'Богородское', 'country': 'Россия'},
    {'iata_code': 'BQJ', 'name': 'Батагай', 'country': 'Россия'},
    {'iata_code': 'BQS', 'name': 'Благовещенск', 'country': 'Россия'},
    {'iata_code': 'BQT', 'name': 'Брест', 'country': 'Беларусь'},
    {'iata_code': 'BTK', 'name': 'Братск', 'country': 'Россия'},
    {'iata_code': 'BUS', 'name': 'Батуми', 'country': 'Грузия'},
    {'iata_code': 'BVJ', 'name': 'Бованенково', 'country': 'Россия'},
    {'iata_code': 'BXJ', 'name': 'Боралдай', 'country': 'Казахстан'},
    {'iata_code': 'BZK', 'name': 'Брянск', 'country': 'Россия'},
    {'iata_code': 'CEE', 'name': 'Череповец', 'country': 'Россия'},
    {'iata_code': 'CEK', 'name': 'Челябинск', 'country': 'Россия'},
    {'iata_code': 'CFU', 'name': 'Корфу', 'country': 'Греция'},
    {'iata_code': 'CIT', 'name': 'Шымкент', 'country': 'Казахстан'},
    {'iata_code': 'CKH', 'name': 'Чокурдах', 'country': 'Россия'},
    {'iata_code': 'CRZ', 'name': 'Туркменабат', 'country': 'Туркменистан'},
    {'iata_code': 'CSH', 'name': 'Соловки', 'country': 'Россия'},
    {'iata_code': 'CSY', 'name': 'Чебоксары', 'country': 'Россия'},
    {'iata_code': 'CYX', 'name': 'Черский', 'country': 'Россия'},
    {'iata_code': 'DEE', 'name': 'Менделеево', 'country': 'Россия'},
    {'iata_code': 'DKS', 'name': 'Диксон', 'country': 'Россия'},
    {'iata_code': 'DLM', 'name': 'Даламан', 'country': 'Турция'},
    {'iata_code': 'DMB', 'name': 'Тараз', 'country': 'Казахстан'},
    {'iata_code': 'DME', 'name': 'Домодедово', 'country': 'Россия'},
    {'iata_code': 'DPT', 'name': 'Депутатский', 'country': 'Россия'},
    {'iata_code': 'DXB', 'name': 'Дубай', 'country': 'ОАЭ'},
    {'iata_code': 'DYR', 'name': 'Анадырь', 'country': 'Россия'},
    {'iata_code': 'DYU', 'name': 'Душанбе', 'country': 'Таджикистан'},
    {'iata_code': 'DZN', 'name': 'Жезказган', 'country': 'Казахстан'},
    {'iata_code': 'EGO', 'name': 'Белгород', 'country': 'Россия'},
    {'iata_code': 'EIE', 'name': 'Енисейск', 'country': 'Россия'},
    {'iata_code': 'EKS', 'name': 'Шахтерск', 'country': 'Россия'},
    {'iata_code': 'EPU', 'name': 'Пярну', 'country': 'Эстония'},
    {'iata_code': 'ERG', 'name': 'Ербогачён', 'country': 'Россия'},
    {'iata_code': 'ESB', 'name': 'Анкара', 'country': 'Турция'},
    {'iata_code': 'ESL', 'name': 'Элиста', 'country': 'Россия'},
    {'iata_code': 'EVN', 'name': 'Ереван', 'country': 'Армения'},
    {'iata_code': 'EYK', 'name': 'Белоярский', 'country': 'Россия'},
    {'iata_code': 'EZV', 'name': 'Березово', 'country': 'Россия'},
    {'iata_code': 'FEG', 'name': 'Фергана', 'country': 'Узбекистан'},
    {'iata_code': 'FRU', 'name': 'Манас', 'country': 'Кыргызстан'},
    {'iata_code': 'GBB', 'name': 'Габала', 'country': 'Азербайджан'},
    {'iata_code': 'GDX', 'name': 'Магадан', 'country': 'Россия'},
    {'iata_code': 'GDZ', 'name': 'Геленджик', 'country': 'Россия'},
    {'iata_code': 'GME', 'name': 'Гомель', 'country': 'Беларусь'},
    {'iata_code': 'GNA', 'name': 'Гродно', 'country': 'Беларусь'},
    {'iata_code': 'GOJ', 'name': 'Нижний Новгород', 'country': 'Россия'},
    {'iata_code': 'GRV', 'name': 'Грозный', 'country': 'Россия'},
    {'iata_code': 'GSV', 'name': 'Гагарин', 'country': 'Россия'},
    {'iata_code': 'GUW', 'name': 'Атырау', 'country': 'Казахстан'},
    {'iata_code': 'GVN', 'name': 'Советская Гавань', 'country': 'Россия'},
    {'iata_code': 'GYD', 'name': 'Баку', 'country': 'Азербайджан'},
    {'iata_code': 'GYG', 'name': 'Маган', 'country': 'Россия'},
    {'iata_code': 'GZP', 'name': 'Аланья (Газипаша)', 'country': 'Турция'},
    {'iata_code': 'HEL', 'name': 'Хельсинки', 'country': 'Финляндия'},
    {'iata_code': 'HER', 'name': 'Ираклион', 'country': 'Греция'},
    {'iata_code': 'HMA', 'name': 'Ханты-Мансийск', 'country': 'Россия'},
    {'iata_code': 'HTA', 'name': 'Чита', 'country': 'Россия'},
    {'iata_code': 'HTG', 'name': 'Хатанга', 'country': 'Россия'},
    {'iata_code': 'IAA', 'name': 'Игарка', 'country': 'Россия'},
    {'iata_code': 'IAR', 'name': 'Ярославль', 'country': 'Россия'},
    {'iata_code': 'IEV', 'name': 'Жуляны', 'country': 'Украина'},
    {'iata_code': 'IGT', 'name': 'Магас', 'country': 'Россия'},
    {'iata_code': 'IJK', 'name': 'Ижевск', 'country': 'Россия'},
    {'iata_code': 'IKS', 'name': 'Тикси', 'country': 'Россия'},
    {'iata_code': 'IKT', 'name': 'Иркутск', 'country': 'Россия'},
    {'iata_code': 'IKU', 'name': 'Иссык-Куль', 'country': 'Кыргызстан'},
    {'iata_code': 'INA', 'name': 'Инта', 'country': 'Россия'},
    {'iata_code': 'IRM', 'name': 'Игрим', 'country': 'Россия'},
    {'iata_code': 'IST', 'name': 'Стамбул', 'country': 'Турция'},
    {'iata_code': 'ITU', 'name': 'Ясный (Итуруп)', 'country': 'Россия'},
    {'iata_code': 'IWA', 'name': 'Иваново', 'country': 'Россия'},
    {'iata_code': 'JOK', 'name': 'Йошкар-Ола', 'country': 'Россия'},
    {'iata_code': 'KBP', 'name': 'Борисполь', 'country': 'Украина'},
    {'iata_code': 'KCK', 'name': 'Киренск', 'country': 'Россия'},
    {'iata_code': 'KDL', 'name': 'Кярдла', 'country': 'Эстония'},
    {'iata_code': 'KDY', 'name': 'Хандыга', 'country': 'Россия'},
    {'iata_code': 'KEJ', 'name': 'Кемерово', 'country': 'Россия'},
    {'iata_code': 'KGD', 'name': 'Калининград', 'country': 'Россия'},
    {'iata_code': 'KGF', 'name': 'Караганда', 'country': 'Казахстан'},
    {'iata_code': 'KGP', 'name': 'Когалым', 'country': 'Россия'},
    {'iata_code': 'KGS', 'name': 'Кос', 'country': 'Греция'},
    {'iata_code': 'KHV', 'name': 'Хабаровск', 'country': 'Россия'},
    {'iata_code': 'KIV', 'name': 'Кишинев', 'country': 'Молдова'},
    {'iata_code': 'KJA', 'name': 'Красноярск', 'country': 'Россия'},
    {'iata_code': 'KKQ', 'name': 'Красноселькуп', 'country': 'Россия'},
    {'iata_code': 'KLF', 'name': 'Калуга', 'country': 'Россия'},
    {'iata_code': 'KMW', 'name': 'Кострома', 'country': 'Россия'},
    {'iata_code': 'KOV', 'name': 'Кокшетау', 'country': 'Казахстан'},
    {'iata_code': 'KPJ', 'name': 'Каракол', 'country': 'Кыргызстан'},
    {'iata_code': 'KQT', 'name': 'Бохтар', 'country': 'Таджикистан'},
    {'iata_code': 'KRO', 'name': 'Курган', 'country': 'Россия'},
    {'iata_code': 'KRR', 'name': 'Краснодар', 'country': 'Россия'},
    {'iata_code': 'KRW', 'name': 'Туркменбаши', 'country': 'Туркменистан'},
    {'iata_code': 'KSN', 'name': 'Костанай', 'country': 'Казахстан'},
    {'iata_code': 'KSQ', 'name': 'Карши', 'country': 'Узбекистан'},
    {'iata_code': 'KSZ', 'name': 'Котлас', 'country': 'Россия'},
    {'iata_code': 'KUF', 'name': 'Самара', 'country': 'Россия'},
    {'iata_code': 'KUN', 'name': 'Каунас', 'country': 'Литва'},
    {'iata_code': 'KUT', 'name': 'Кутаиси', 'country': 'Грузия'},
    {'iata_code': 'KVD', 'name': 'Гянджа', 'country': 'Азербайджан'},
    {'iata_code': 'KVK', 'name': 'Апатиты', 'country': 'Россия'},
    {'iata_code': 'KVM', 'name': 'Марково', 'country': 'Россия'},
    {'iata_code': 'KVR', 'name': 'Кавалерово', 'country': 'Россия'},
    {'iata_code': 'KVX', 'name': 'Киров', 'country': 'Россия'},
    {'iata_code': 'KXK', 'name': 'Комсомольск-на-Амуре', 'country': 'Россия'},
    {'iata_code': 'KYZ', 'name': 'Кызыл', 'country': 'Россия'},
    {'iata_code': 'KZN', 'name': 'Казань', 'country': 'Россия'},
    {'iata_code': 'KZO', 'name': 'Кызылорда', 'country': 'Казахстан'},
    {'iata_code': 'LBD', 'name': 'Худжанд', 'country': 'Таджикистан'},
    {'iata_code': 'LCA', 'name': 'Ларнака', 'country': 'Республика Кипр'},
    {'iata_code': 'LDG', 'name': 'Лешуконское', 'country': 'Россия'},
    {'iata_code': 'LED', 'name': 'Пулково', 'country': 'Россия'},
    {'iata_code': 'LLK', 'name': 'Ленкорань', 'country': 'Азербайджан'},
    {'iata_code': 'LPK', 'name': 'Липецк', 'country': 'Россия'},
    {'iata_code': 'LPP', 'name': 'Лаппеэнранта', 'country': 'Финляндия'},
    {'iata_code': 'LWN', 'name': 'Ширак (Гюмри)', 'country': 'Армения'},
    {'iata_code': 'MCX', 'name': 'Махачкала', 'country': 'Россия'},
    {'iata_code': 'MJZ', 'name': 'Мирный', 'country': 'Россия'},
    {'iata_code': 'MMK', 'name': 'Мурманск', 'country': 'Россия'},
    {'iata_code': 'MMW', 'name': 'Мома', 'country': 'Россия'},
    {'iata_code': 'MQF', 'name': 'Магнитогорск', 'country': 'Россия'},
    {'iata_code': 'MRV', 'name': 'Минеральные Воды', 'country': 'Россия'},
    {'iata_code': 'MSQ', 'name': 'Минск', 'country': 'Беларусь'},
    {'iata_code': 'MVQ', 'name': 'Могилев', 'country': 'Беларусь'},
    {'iata_code': 'MYP', 'name': 'Мары', 'country': 'Туркменистан'},
    {'iata_code': 'NAJ', 'name': 'Нахичевань', 'country': 'Азербайджан'},
    {'iata_code': 'NAL', 'name': 'Нальчик', 'country': 'Россия'},
    {'iata_code': 'NBC', 'name': 'Бегишево', 'country': 'Россия'},
    {'iata_code': 'NCU', 'name': 'Нукус', 'country': 'Узбекистан'},
    {'iata_code': 'NER', 'name': 'Нерюнгри', 'country': 'Россия'},
    {'iata_code': 'NGK', 'name': 'Ноглики', 'country': 'Россия'},
    {'iata_code': 'NJC', 'name': 'Нижневартовск', 'country': 'Россия'},
    {'iata_code': 'NLI', 'name': 'Николаевск-на-Амуре', 'country': 'Россия'},
    {'iata_code': 'NMA', 'name': 'Наманаган', 'country': 'Узбекистан'},
    {'iata_code': 'NNM', 'name': 'Нарьян-Мар', 'country': 'Россия'},
    {'iata_code': 'NOJ', 'name': 'Ноябрьск', 'country': 'Россия'},
    {'iata_code': 'NOZ', 'name': 'Новокузнецк', 'country': 'Россия'},
    {'iata_code': 'NQZ', 'name': 'Нурсултан', 'country': 'Казахстан'},
    {'iata_code': 'NSK', 'name': 'Норильск', 'country': 'Россия'},
    {'iata_code': 'NUX', 'name': 'Новый Уренгой', 'country': 'Россия'},
    {'iata_code': 'NVI', 'name': 'Навои', 'country': 'Узбекистан'},
    {'iata_code': 'NYA', 'name': 'Нягань', 'country': 'Россия'},
    {'iata_code': 'NYM', 'name': 'Надым', 'country': 'Россия'},
    {'iata_code': 'NYR', 'name': 'Нюрба', 'country': 'Россия'},
    {'iata_code': 'ODO', 'name': 'Бодайбо', 'country': 'Россия'},
    {'iata_code': 'OGZ', 'name': 'Владикавказ', 'country': 'Россия'},
    {'iata_code': 'OHH', 'name': 'Оха', 'country': 'Россия'},
    {'iata_code': 'OHO', 'name': 'Охотск', 'country': 'Россия'},
    {'iata_code': 'OLZ', 'name': 'Олёкминск', 'country': 'Россия'},
    {'iata_code': 'OMS', 'name': 'Омск', 'country': 'Россия'},
    {'iata_code': 'ONK', 'name': 'Оленёк', 'country': 'Россия'},
    {'iata_code': 'OSF', 'name': 'Остафьево', 'country': 'Россия'},
    {'iata_code': 'OSS', 'name': 'Ош', 'country': 'Кыргызстан'},
    {'iata_code': 'OSW', 'name': 'Орск', 'country': 'Россия'},
    {'iata_code': 'OVB', 'name': 'Толмачево', 'country': 'Россия'},
    {'iata_code': 'OVS', 'name': 'Советский', 'country': 'Россия'},
    {'iata_code': 'PEE', 'name': 'Пермь', 'country': 'Россия'},
    {'iata_code': 'PES', 'name': 'Петрозаводск', 'country': 'Россия'},
    {'iata_code': 'PEX', 'name': 'Печора', 'country': 'Россия'},
    {'iata_code': 'PEZ', 'name': 'Пенза', 'country': 'Россия'},
    {'iata_code': 'PKC', 'name': 'Елизово', 'country': 'Россия'},
    {'iata_code': 'PKV', 'name': 'Псков', 'country': 'Россия'},
    {'iata_code': 'PLQ', 'name': 'Паланга', 'country': 'Литва'},
    {'iata_code': 'PLX', 'name': 'Семей', 'country': 'Казахстан'},
    {'iata_code': 'PPK', 'name': 'Петропавловск', 'country': 'Казахстан'},
    {'iata_code': 'PVS', 'name': 'Провидения Бухта', 'country': 'Россия'},
    {'iata_code': 'PWE', 'name': 'Певек', 'country': 'Россия'},
    {'iata_code': 'PWQ', 'name': 'Павлодар', 'country': 'Казахстан'},
    {'iata_code': 'PYJ', 'name': 'Полярный', 'country': 'Россия'},
    {'iata_code': 'REN', 'name': 'Оренбург', 'country': 'Россия'},
    {'iata_code': 'RGK', 'name': 'Горно-Алтайск', 'country': 'Россия'},
    {'iata_code': 'RHO', 'name': 'Родос', 'country': 'Греция'},
    {'iata_code': 'RIX', 'name': 'Рига', 'country': 'Латвия'},
    {'iata_code': 'RMZ', 'name': 'Тобольск (Ремезов)', 'country': 'Россия'},
    {'iata_code': 'ROV', 'name': 'Платов', 'country': 'Россия'},
    {'iata_code': 'SBT', 'name': 'Сабетта', 'country': 'Россия'},
    {'iata_code': 'SCO', 'name': 'Актау', 'country': 'Казахстан'},
    {'iata_code': 'SCW', 'name': 'Сыктывкар', 'country': 'Россия'},
    {'iata_code': 'SEK', 'name': 'Среднеколымск', 'country': 'Россия'},
    {'iata_code': 'SGC', 'name': 'Сургут', 'country': 'Россия'},
    {'iata_code': 'SIP', 'name': 'Симферополь', 'country': 'Россия'},
    {'iata_code': 'SKD', 'name': 'Самарканд', 'country': 'Узбекистан'},
    {'iata_code': 'SKG', 'name': 'Салоники', 'country': 'Греция'},
    {'iata_code': 'SKX', 'name': 'Саранск', 'country': 'Россия'},
    {'iata_code': 'SLY', 'name': 'Салехард', 'country': 'Россия'},
    {'iata_code': 'SQQ', 'name': 'Шяуляй', 'country': 'Литва'},
    {'iata_code': 'STW', 'name': 'Ставрополь', 'country': 'Россия'},
    {'iata_code': 'SUK', 'name': 'Саккырыр', 'country': 'Россия'},
    {'iata_code': 'SUY', 'name': 'Сунтар', 'country': 'Россия'},
    {'iata_code': 'SVO', 'name': 'Шереметьево', 'country': 'Россия'},
    {'iata_code': 'SVX', 'name': 'Кольцово', 'country': 'Россия'},
    {'iata_code': 'SWT', 'name': 'Стрежевой', 'country': 'Россия'},
    {'iata_code': 'SWV', 'name': 'Северо-Эвенск', 'country': 'Россия'},
    {'iata_code': 'SYS', 'name': 'Саскылах', 'country': 'Россия'},
    {'iata_code': 'TAS', 'name': 'Ташкент', 'country': 'Узбекистан'},
    {'iata_code': 'TAY', 'name': 'Тарту', 'country': 'Эстония'},
    {'iata_code': 'TAZ', 'name': 'Дашогуз', 'country': 'Туркменистан'},
    {'iata_code': 'TBS', 'name': 'Тбилиси', 'country': 'Грузия'},
    {'iata_code': 'TBW', 'name': 'Тамбов', 'country': 'Россия'},
    {'iata_code': 'TDK', 'name': 'Талдыкорган', 'country': 'Казахстан'},
    {'iata_code': 'TGP', 'name': 'Подкаменная Тунгуска', 'country': 'Россия'},
    {'iata_code': 'THX', 'name': 'Туруханск', 'country': 'Россия'},
    {'iata_code': 'TJM', 'name': 'Тюмень', 'country': 'Россия'},
    {'iata_code': 'TJU', 'name': 'Куляб', 'country': 'Таджикистан'},
    {'iata_code': 'TLK', 'name': 'Талакан', 'country': 'Россия'},
    {'iata_code': 'TLL', 'name': 'Таллинн', 'country': 'Эстония'},
    {'iata_code': 'TLV', 'name': 'Тель-Авив', 'country': 'Израиль'},
    {'iata_code': 'TLY', 'name': 'Пластун', 'country': 'Россия'},
    {'iata_code': 'TMJ', 'name': 'Термез', 'country': 'Узбекистан'},
    {'iata_code': 'TOF', 'name': 'Томск', 'country': 'Россия'},
    {'iata_code': 'TQL', 'name': 'Тарко-Сале', 'country': 'Россия'},
    {'iata_code': 'TYD', 'name': 'Тында', 'country': 'Россия'},
    {'iata_code': 'UCT', 'name': 'Ухта', 'country': 'Россия'},
    {'iata_code': 'UFA', 'name': 'Уфа', 'country': 'Россия'},
    {'iata_code': 'UGC', 'name': 'Ургенч', 'country': 'Узбекистан'},
    {'iata_code': 'UKG', 'name': 'Усть-Куйга', 'country': 'Россия'},
    {'iata_code': 'UKK', 'name': 'Усть-Каменогорск', 'country': 'Казахстан'},
    {'iata_code': 'UKX', 'name': 'Усть-Кут', 'country': 'Россия'},
    {'iata_code': 'ULK', 'name': 'Ленск', 'country': 'Россия'},
    {'iata_code': 'ULV', 'name': 'Ульяновск', 'country': 'Россия'},
    {'iata_code': 'ULY', 'name': 'Ульяновск (Восточный)', 'country': 'Россия'},
    {'iata_code': 'UMS', 'name': 'Усть-Мая', 'country': 'Россия'},
    {'iata_code': 'URA', 'name': 'Уральск', 'country': 'Казахстан'},
    {'iata_code': 'URE', 'name': 'Курессааре', 'country': 'Эстония'},
    {'iata_code': 'URJ', 'name': 'Урай', 'country': 'Россия'},
    {'iata_code': 'URS', 'name': 'Курск', 'country': 'Россия'},
    {'iata_code': 'USK', 'name': 'Усинск', 'country': 'Россия'},
    {'iata_code': 'USP', 'name': 'Усть-Нера', 'country': 'Россия'},
    {'iata_code': 'UTS', 'name': 'Усть-Цильма', 'country': 'Россия'},
    {'iata_code': 'UUA', 'name': 'Бугульма', 'country': 'Россия'},
    {'iata_code': 'UUD', 'name': 'Улан-Удэ', 'country': 'Россия'},
    {'iata_code': 'UUS', 'name': 'Южно-Сахалинск', 'country': 'Россия'},
    {'iata_code': 'VGD', 'name': 'Вологда', 'country': 'Россия'},
    {'iata_code': 'VHV', 'name': 'Верхневилюйск', 'country': 'Россия'},
    {'iata_code': 'VKO', 'name': 'Внуково', 'country': 'Россия'},
    {'iata_code': 'VKT', 'name': 'Воркута', 'country': 'Россия'},
    {'iata_code': 'VNO', 'name': 'Вильнюс', 'country': 'Литва'},
    {'iata_code': 'VNT', 'name': 'Вентспилс', 'country': 'Латвия'},
    {'iata_code': 'VOG', 'name': 'Волгоград', 'country': 'Россия'},
    {'iata_code': 'VOZ', 'name': 'Воронеж', 'country': 'Россия'},
    {'iata_code': 'VTB', 'name': 'Витебск', 'country': 'Беларусь'},
    {'iata_code': 'VUS', 'name': 'Великий Устюг', 'country': 'Россия'},
    {'iata_code': 'VVO', 'name': 'Владивосток', 'country': 'Россия'},
    {'iata_code': 'VYI', 'name': 'Вилюйск', 'country': 'Россия'},
    {'iata_code': 'YKS', 'name': 'Якутск', 'country': 'Россия'},
    {'iata_code': 'ZIA', 'name': 'Жуковский', 'country': 'Россия'},
    {'iata_code': 'ZIX', 'name': 'Жиганск', 'country': 'Россия'},
    {'iata_code': 'ZKP', 'name': 'Зырянка', 'country': 'Россия'},
    {'iata_code': 'ZTU', 'name': 'Парзиван', 'country': 'Азербайджан'},
]

carriers = [
    {'id': 1, 'name': 'Aeroflot', 'logo': 'http://test.ru/image.jpg'},
    {'id': 2, 'name': 'Pegasus', 'logo': 'http://test.ru/image.jpg'},
]


def get_airport_by_iata(iata_code):
    try:
        return next(airport for airport in airpotr_list
                    if airport["iata_code"] == iata_code)
    except StopIteration:
        return None


def get_departure_date_and_delta(departure_date):
    new_date = max(departure_date, datetime.now())
    delta = (datetime.now().replace(hour=23, minute=59, second=59) - new_date)
    return new_date, delta.seconds


def generate_departure_date(departure_date, delta_in_seconds=86399):
    return (departure_date + random.random()
            * timedelta(seconds=delta_in_seconds)).replace(second=0)
